title: Placement & Interview Prep
search_enabled: true
color_scheme: light

nav_sort: case_insensitive

just_the_docs:
  aux_links:
    "GitHub Repo":
      - "https://gitb.sgy.co.in/Coding-and-Training"
